In [1]:
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset=load_iris()
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [2]:
#langkah1 mengetahui data itu dari mana
print(type(dataset))
print(len(dataset))
#menyisir format dataset tersebut. dengan objek.
print(dataset.keys())
#mencoba untuk mencari nilai yang ada di riwayat dengan atribut
print(dataset['data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])
#lanjutkan untuk menentukan x dan y; y memiliki ketergantungan dari x
x=dataset['data']
print(len(x)) #untuk memeriksa panjangnya dataset
y=dataset['target']
print(len(y)) #untuk memeriksa panjangnya targets
print(x[0])
print(y[0])

<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [3]:
#langkah 2 Ubah Y menjadi satu vektor yang dikodekan teratas
#kode teratas adalah penggunaan karena y termasuk label (0,1,2)- yang mana kategori data dengan bukan hubungan ordinal
from keras.utils import to_categorical
Ny=len(np.unique(y))
print(Ny)
Y=to_categorical(y,num_classes=Ny)
print(Y[0:5])

3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [6]:
#langkah 3 : sekarang kami akan memecah data sampai 2 bagian - 1 untuk data latih dan lainnya untuk untuk data testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])

[[5.1 3.7 1.5 0.4]
 [6.5 3.2 5.1 2. ]
 [5.4 3.4 1.5 0.4]
 [6.7 3.3 5.7 2.1]
 [7.4 2.8 6.1 1.9]]
[[6.7 3.1 4.7 1.5]
 [6.3 2.7 4.9 1.8]
 [6.8 3.2 5.9 2.3]
 [6.6 2.9 4.6 1.3]
 [5.1 3.3 1.7 0.5]]
[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [7]:
#langkah 4 :kemudian menormlakan data
from sklearn.preprocessing import StandardScaler
#selesai menormalkan data lalu membedakan antara tertinggi dan terendah suatu data point yang tidak besar juga
import numpy as np
scaler=StandardScaler()
#untuk mencari rata-rata dan standar dev
scaler.fit(x_train)

#mengubah data menjadi bentuk dimana rata-rata dari data adalah 0 dan std dev adalah 1
X_train=scaler.transform(x_train)
X_test=scaler.transform(x_test)
print(np.amax(X_train,axis=0))
print(np.amin(X_train,axis=0))

[2.4316154  3.01152434 1.75609941 1.67858015]
[-1.86258912 -2.4212924  -1.53969036 -1.4150488 ]


In [8]:
#langkah ke5 : terakhir membuat model dari keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=X_train.shape[1], activation='relu'))
#Dropout untuk menghindari overfitting
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
#untuk mengkalsifikasikan masalah, biasanya menggunakan softmax untuk aktifasi fungsi di akhir lapisan
model.add(Dense(3, activation='softmax'))
#kompilasi model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
#langkah ke 6 : mengetahui model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                100       
                                                                 
 dense_1 (Dense)             (None, 20)                420       
                                                                 
 dense_2 (Dense)             (None, 20)                420       
                                                                 
 dense_3 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [11]:
#langkah ke 7 : melatih model
#Batch ukuran,epoch dan validasi membelah semua hyper parameters
model.fit(X_train, y_train, epochs=195, batch_size=80, validation_split=0.1)

Epoch 1/195
2/2 [==============================] - 7s 2s/step - loss: 1.1198 - accuracy: 0.2479 - val_loss: 1.0388 - val_accuracy: 0.5000
Epoch 2/195
2/2 [==============================] - 0s 64ms/step - loss: 1.0950 - accuracy: 0.2810 - val_loss: 1.0254 - val_accuracy: 0.6429
Epoch 3/195
2/2 [==============================] - 0s 41ms/step - loss: 1.0709 - accuracy: 0.3554 - val_loss: 1.0121 - val_accuracy: 0.6429
Epoch 4/195
2/2 [==============================] - 0s 46ms/step - loss: 1.0482 - accuracy: 0.4215 - val_loss: 0.9992 - val_accuracy: 0.6429
Epoch 5/195
2/2 [==============================] - 0s 36ms/step - loss: 1.0279 - accuracy: 0.4793 - val_loss: 0.9868 - val_accuracy: 0.5714
Epoch 6/195
2/2 [==============================] - 0s 58ms/step - loss: 1.0063 - accuracy: 0.4959 - val_loss: 0.9750 - val_accuracy: 0.5000
Epoch 7/195
2/2 [==============================] - 0s 47ms/step - loss: 0.9866 - accuracy: 0.5041 - val_loss: 0.9634 - val_accuracy: 0.5000
Epoch 8/195
2/2 [=====

2/2 [==============================] - 0s 44ms/step - loss: 0.2836 - accuracy: 0.9091 - val_loss: 0.5998 - val_accuracy: 0.5714
Epoch 60/195
2/2 [==============================] - 0s 47ms/step - loss: 0.2764 - accuracy: 0.9091 - val_loss: 0.5965 - val_accuracy: 0.5714
Epoch 61/195
2/2 [==============================] - 0s 44ms/step - loss: 0.2697 - accuracy: 0.9091 - val_loss: 0.5935 - val_accuracy: 0.5714
Epoch 62/195
2/2 [==============================] - 0s 43ms/step - loss: 0.2629 - accuracy: 0.9091 - val_loss: 0.5898 - val_accuracy: 0.5714
Epoch 63/195
2/2 [==============================] - 0s 42ms/step - loss: 0.2563 - accuracy: 0.9091 - val_loss: 0.5853 - val_accuracy: 0.5714
Epoch 64/195
2/2 [==============================] - 0s 41ms/step - loss: 0.2503 - accuracy: 0.9091 - val_loss: 0.5795 - val_accuracy: 0.5714
Epoch 65/195
2/2 [==============================] - 0s 42ms/step - loss: 0.2443 - accuracy: 0.9091 - val_loss: 0.5727 - val_accuracy: 0.5714
Epoch 66/195
2/2 [========

2/2 [==============================] - 0s 44ms/step - loss: 0.0865 - accuracy: 0.9752 - val_loss: 0.1961 - val_accuracy: 0.8571
Epoch 118/195
2/2 [==============================] - 0s 47ms/step - loss: 0.0857 - accuracy: 0.9752 - val_loss: 0.1960 - val_accuracy: 0.8571
Epoch 119/195
2/2 [==============================] - 0s 44ms/step - loss: 0.0842 - accuracy: 0.9752 - val_loss: 0.1918 - val_accuracy: 0.8571
Epoch 120/195
2/2 [==============================] - 0s 37ms/step - loss: 0.0832 - accuracy: 0.9752 - val_loss: 0.1874 - val_accuracy: 0.9286
Epoch 121/195
2/2 [==============================] - 0s 48ms/step - loss: 0.0818 - accuracy: 0.9752 - val_loss: 0.1780 - val_accuracy: 0.9286
Epoch 122/195
2/2 [==============================] - 0s 47ms/step - loss: 0.0805 - accuracy: 0.9752 - val_loss: 0.1693 - val_accuracy: 0.9286
Epoch 123/195
2/2 [==============================] - 0s 48ms/step - loss: 0.0792 - accuracy: 0.9669 - val_loss: 0.1612 - val_accuracy: 1.0000
Epoch 124/195
2/2 [=

Epoch 175/195
2/2 [==============================] - 0s 48ms/step - loss: 0.0474 - accuracy: 0.9835 - val_loss: 0.0512 - val_accuracy: 1.0000
Epoch 176/195
2/2 [==============================] - 0s 49ms/step - loss: 0.0472 - accuracy: 0.9835 - val_loss: 0.0511 - val_accuracy: 1.0000
Epoch 177/195
2/2 [==============================] - 0s 47ms/step - loss: 0.0463 - accuracy: 0.9835 - val_loss: 0.0531 - val_accuracy: 1.0000
Epoch 178/195
2/2 [==============================] - 0s 48ms/step - loss: 0.0460 - accuracy: 0.9835 - val_loss: 0.0548 - val_accuracy: 1.0000
Epoch 179/195
2/2 [==============================] - 0s 51ms/step - loss: 0.0456 - accuracy: 0.9835 - val_loss: 0.0552 - val_accuracy: 1.0000
Epoch 180/195
2/2 [==============================] - 0s 46ms/step - loss: 0.0456 - accuracy: 0.9835 - val_loss: 0.0552 - val_accuracy: 1.0000
Epoch 181/195
2/2 [==============================] - 0s 48ms/step - loss: 0.0451 - accuracy: 0.9835 - val_loss: 0.0536 - val_accuracy: 1.0000
Epoch 

In [13]:
#langkah 8 : mengambil akurasi dari model di data uji
testing=model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1]+' dari model data uji', testing[1]*100))

1/1 [==============================] - 0s 36ms/step - loss: 1.0492 - accuracy: 0.8667

accuracy dari model data uji: 86.67%


In [14]:
#langkah 9 : mengevaluasi model lain
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(X_test), axis=1)
Y_test = np.argmax(y_test, axis=1)
# mengambil confusion matrix
print(confusion_matrix(Y_test, predictions))
# mengambil nilai dari semua evaluation matrics
print(classification_report(Y_test,predictions))

1/1 [==============================] - 0s 169ms/step
[[4 0 0]
 [0 7 0]
 [0 2 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       0.78      1.00      0.88         7
           2       1.00      0.50      0.67         4

    accuracy                           0.87        15
   macro avg       0.93      0.83      0.85        15
weighted avg       0.90      0.87      0.85        15

